# 1.Print 'Hello HCIA'.

In [1]:
'Hello HCIA'

'Hello HCIA'

# 2.Define two variables and calculate their sum.

In [2]:
a=2
b=5
a+b

7

# 3.Define a list and replicate in three different ways.

In [3]:
aa=['one','two','three']
a1 = aa.copy()
a2 = aa.copy()
a3 = aa.copy()
print(a1)
print(a2)
print(a3)

['one', 'two', 'three']
['one', 'two', 'three']
['one', 'two', 'three']


# 4.Define two lists and merge them together.

In [4]:
ab=['1','2']
ba=['3','4']
ab.extend(ba)
ab

['1', '2', '3', '4']

# 5. Get the last element of the list and print it.

In [5]:
listing=['one','two,','three',4,5]
listing[-1]

5

# 6.Define a tuple that contains only one element.

In [6]:
tup=tuple('proba')
print(type(tup))
tup

<class 'tuple'>


('p', 'r', 'o', 'b', 'a')

# 7.Define a three-line long string.

In [7]:
'''
proba
one
two'''

'\nproba\none\ntwo'

# 8.Define a tuple and then use the 'for loop' to print all the elements.

In [8]:
a = (1,2,3,4,5,6,7,8,9,0)
for loop in a:
    print(loop)

1
2
3
4
5
6
7
8
9
0


# 9.Define a function to do Multiplication, such as Mul(8,6),and its output 48.

In [14]:
def func(x,y):
    z = x * y
    print(z)
func(8,6)

48


# 10.Import numpy and use numpy to define an array, the its shape  is (5,5) and all its elements is 0.

In [15]:
import numpy as np
np.zeros(25).reshape(5,5)

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

# 11.Import numpy and use numpy to define an array, the shape is (4,6) and all elements is 0.

In [16]:
import numpy as np
np.zeros(24).reshape(4,6)

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

# 12.Use numpy.arrange() to generate an array of shape(15,), then modify the shape to(3,5).

In [17]:
w = np.arange(15)
w.reshape(3,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

# 13.Define two matrices, then calculate and print the result of their point multiplication.

In [18]:
z1 = np.arange(25).reshape(5,5)
z2 = np.arange(5,30).reshape(5,5)
z1 * z2

array([[  0,   6,  14,  24,  36],
       [ 50,  66,  84, 104, 126],
       [150, 176, 204, 234, 266],
       [300, 336, 374, 414, 456],
       [500, 546, 594, 644, 696]])